In [1]:
import numpy as np

In [3]:
"""
    在[0, 1, 1] 三个数中，随机选10个，因为1有两个，所以结果中 1 会比较多
"""

a = np.random.choice([0, 1, 1], 10)

print(a)

[1 1 0 1 1 1 1 1 1 0]


In [5]:
'''
    写一个参数 与 写两个参数的区别；一个是一维，一个是二维
'''
b1 = np.zeros([3,])
print('b1:\n', b1)

b2 = np.zeros([3,1])
print('b2:\n ', b2)


b1:
 [0. 0. 0.]
b2:
  [[0.]
 [0.]
 [0.]]
