In [2]:
import numpy as np

In [3]:
"""
    在[0, 1, 1] 三个数中，随机选10个，因为1有两个，所以结果中 1 会比较多
"""

a = np.random.choice([0, 1, 1], 10)

print(a)

[1 1 0 1 1 1 1 1 1 0]


In [5]:
'''
    写一个参数 与 写两个参数的区别；一个是一维，一个是二维
'''
b1 = np.zeros([3,])
print('b1:\n', b1)

b2 = np.zeros([3,1])
print('b2:\n ', b2)


b1:
 [0. 0. 0.]
b2:
  [[0.]
 [0.]
 [0.]]


In [30]:
"""
    c:  在 (0,5) 之前随机选取一个值
    
    c_list: 随机10次, 验证了确实是在 (0,5) 之间
"""

c = np.random.randint(0,5)
print(c)


c_list = []
for i in range(10):
    c = np.random.randint(0,5)
    c_list.append(c)

print(c_list)

4
[4, 1, 0, 0, 4, 2, 1, 1, 1, 1]


In [31]:
"""
    测试 np.repeat; 原来这里是一维的重复
"""


d = np.repeat(np.random.choice([0,1,1], 5), 3)

print(d)

[1 1 1 1 1 1 0 0 0 1 1 1 1 1 1]


In [44]:

"""
    逐 元素 相乘 multiply
"""
import numpy as np

# 创建两个一维数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 使用multiply函数进行逐元素乘法
c = np.multiply(a, b)

print(c)  # 输出： [ 4 10 18]

print('-'*20)

# 创建一个二维数组（矩阵）
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6], [7, 8]])

# 使用multiply函数进行逐元素乘法
f = np.multiply(d, e)

print(f)



[ 4 10 18]
--------------------
[[ 5 12]
 [21 32]]


In [61]:

"""
    测试 multiply 和 dot 的区别

    在NumPy中, multiply函数 实际上执行的是矩阵与标量的乘法, 也就是将一个矩阵(或数组) 的每个元素与一个标量相乘。
    
    这种操作并不执行矩阵乘法，即不会按照矩阵乘法的规则去计算两个矩阵的乘积。
"""
data = np.array([i for i in range(5)]).reshape(5, 1)
print(data)
print(data.shape)
print('-'*20)

column = np.array([i for i in range(5)])
print(column)
print(column.shape)
print('-'*20)

result = np.multiply(data, column)
print(result)
print(result.shape)
print('-'*20)

# 这是错误演示，这种shape是无法做 矩阵乘法的
res1 = np.dot(data, column)
print(res1)


[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
--------------------
[0 1 2 3 4]
(5,)
--------------------
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
(5, 5)
--------------------


ValueError: shapes (5,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)

In [67]:
"""
    np.linespace 用于生成在指定区间内均匀分布的一维数组
"""

a = np.linspace(0, 4*np.pi, 10)
print(4*np.pi)
print(a)

print('-'*30)

b = np.linspace(0, 9, 10)
print(b)

12.566370614359172
[ 0.          1.3962634   2.7925268   4.1887902   5.58505361  6.98131701
  8.37758041  9.77384381 11.17010721 12.56637061]
------------------------------
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
